name: 05-1-filters-activity-types
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running when PR is opend, sync and on main branch"

