name: 07-expressions
run-name: 07-expression | Debug ${{inputs.debug && 'ON' || 'Off'}}
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print Start-up'
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"
      - name: '[debug] Print Triggered from main'
        if: ${{inputs.debug && github.ref == 'refs/heads/main'}}
        run: echo "Triggered from main"
      - name: Greetings
        run: echo "Hello, World!"

