name: 10-execution-flow
on:
  workflow_dispatch:
    inputs:
      Pass-unit-tests:
        type: boolean
        description: whether unit test will pass or not
        default: true

jobs:

  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: lint and build
        run: |
          # npm run lint
          # npm run format:check
          # npm run tsc:check
          # npm run build
          echo "lint and build project"

  unit-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: running unit tests
        run: |
          echo "running tests..."
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests}}
        run: |
          exit 1

  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-test
    steps:
      - name: Deploying non-prod
        run: |
          echo " Deploying to non-prod..."

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: runing e2e tests
        run: |
          echo "runing e2e tests.."
  
  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: runing load tests
        run: |
          echo "runing load tests.."

  deploy-prod:
    runs-on: ubuntu-latest
    needs:
     - e2e-tests
     - load-tests
    steps:
      - name: running deploy prod
        run: |
          echo "Deploying to Prod"
      

