name: 12-Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      build-status-output: ${{ steps.build.outputs.status }}
    steps:
      - name: Print github output path
        run: |
          echo "$GITHUB_OUTPUT"
      - name: Builds
        id: build
        run: |
          echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT"
  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build
    if: ${{ needs.Build.outputs.build-status-output == 'success'}}
    steps:
      - name: deploy
        run: |
          echo "Deploying.."