name: 16-environments
# run-name: working with environments | env - ${{ inputs.target-env}}
on:
  workflow_dispatch:
    # inputs:
    #   target-env:
    #     type: environment
    #     # this type check the environment section in settings for variables and values but this feature avaiable only for non-organisation  
    #     default: staging
    
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.target-env }}
    environment: staging
    # env:
    #   MY_ENV_Value: ${{ vars.MY_ENV_Value || 'default value'}}
    steps:
      - name: echo-vars
        run: |
          # echo "Env Vars: ${{ env.MY_ENV_Value}}"
          echo "Env Vars: Staging"
  
  deploy-prod-backend:
    # you can set approvers required in settings for prod environment type to run this job
    runs-on: ubuntu-latest
    needs: deploy-staging
    # environment: ${{ inputs.target-env }}
    environment: Prod
    # env:
    #   MY_ENV_Value: ${{ vars.MY_ENV_Value || 'default value'}}
    steps:
      - name: echo-vars
        run: |
          # echo "Env Vars: ${{ env.MY_ENV_Value}}"
          echo "Env Vars: Prod-backend"

  deploy-prod-frontend:
    # you can set approvers required in settings for prod environment type to run this job
    runs-on: ubuntu-latest
    needs: deploy-staging
    # environment: ${{ inputs.target-env }}
    environment: Prod
    # env:
    #   MY_ENV_Value: ${{ vars.MY_ENV_Value || 'default value'}}
    steps:
      - name: echo-vars
        run: |
          # echo "Env Vars: ${{ env.MY_ENV_Value}}"
          echo "Env Vars: Prod-frontend"

