name: 16-environments
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
    
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      MY_ENV_Value: ${{ vars.MY_ENV_Value || 'default value'}}
    steps:
      - name: echo-vars
        run: |
          echo "Env Vars: ${{ env.MY_ENV_Value}}"


